# Generated by Django 5.2.1 on 2025-05-14 18:35

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="blog/")),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneralDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("promptpay", "PromptPay"),
                            ("credit_card", "Credit Card"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "slip_image",
                    models.ImageField(blank=True, null=True, upload_to="slips/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StrayAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_id", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat")], max_length=10
                    ),
                ),
                ("age_value", models.PositiveIntegerField()),
                (
                    "age_unit",
                    models.CharField(
                        choices=[
                            ("day", "Day(s)"),
                            ("week", "Week(s)"),
                            ("month", "Month(s)"),
                            ("year", "Year(s)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                            ("extra large", "Extra Large"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "coat_length",
                    models.CharField(
                        choices=[
                            ("hairless", "Hairless"),
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                            ("wire", "Wire"),
                            ("curly", "Curly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "good_with",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("kids", "Kids"),
                            ("other dogs", "Other Dogs"),
                            ("cats", "Cats"),
                        ],
                        max_length=50,
                        verbose_name="Good with",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("Apricot / Beige", "Apricot / Beige"),
                            ("Bicolor", "Bicolor"),
                            ("Black", "Black"),
                            ("Brindle", "Brindle"),
                            ("Brown/Chocolate", "Brown/Chocolate"),
                            ("Golden", "Golden"),
                            ("Gray/Blue/Silver", "Gray/Blue/Silver"),
                            ("Harlequin", "Harlequin"),
                            ("Merle (Blue)", "Merle (Blue)"),
                            ("Merle (Red)", "Merle (Red)"),
                            ("Red / Chestnut / Orange", "Red / Chestnut / Orange"),
                            ("Sable", "Sable"),
                            (
                                "Tricolor (Brown,Black, & White)",
                                "Tricolor (Brown,Black, & White)",
                            ),
                            ("White / Cream", "White / Cream"),
                            (
                                "Yellow / Tan / Blond / Fawn",
                                "Yellow / Tan / Blond / Fawn",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "care_and_behavior",
                    models.CharField(
                        choices=[
                            ("House-trained", "House-trained"),
                            ("Special Needs", "Special Needs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "days_on_pawpal",
                    models.CharField(
                        choices=[
                            ("Any", "Any"),
                            ("1", "1"),
                            ("7", "7"),
                            ("14", "14"),
                            ("30+", "30+"),
                        ],
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_images/"
                    ),
                ),
                ("story_describe", models.TextField(blank=True)),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("Anxiety", "Anxiety"),
                            ("Barking and Howling", "Barking and Howling"),
                            ("Biting", "Biting"),
                            ("Chewing", "Chewing"),
                            ("Others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("health_status", models.TextField(blank=True)),
                ("is_adopted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SponsorshipDonation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("promptpay", "PromptPay"),
                            ("credit_card", "Credit Card"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_slip",
                    models.ImageField(default=True, upload_to="sponsorship_slips/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adopt.strayanimal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalSponsorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "description",
                    models.TextField(help_text="Explain the medical condition or need"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_support",
                        to="adopt.strayanimal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdoptionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("subdistrict", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("household_info", models.TextField()),
                ("other_pets", models.TextField(blank=True)),
                ("property_description", models.TextField()),
                ("jobs", models.CharField(default="Not specified", max_length=200)),
                ("motivation", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pets",
                    models.ManyToManyField(
                        related_name="adoption_requests", to="adopt.strayanimal"
                    ),
                ),
            ],
        ),
    ]
