# Generated by Django 4.2.20 on 2025-04-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.AddField(
            model_name='pet',
            name='health_issues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='personality',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccination',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Male', 'เพศผู้'), ('Female', 'เพศเมีย')], max_length=10),
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.pet')),
            ],
        ),
    ]
